name: Build Reamix Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]

    steps:
      - name: Set Context
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Initialize
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get install --no-install-recommends -y rpm libopenjp2-tools
          sudo snap install snapcraft --classic
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Build
        run: npm run build
      
      - name: Upload Windows Installer
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-windows-setup
          path: release/${{ steps.extract_version.outputs.version }}/*_setup.exe
      - name: Upload Windows Portable
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-windows-portable
          path: release/${{ steps.extract_version.outputs.version }}/*_portable.exe

      - name: Upload dmg
        if: matrix.os == 'macos-11'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-macos-dmg
          path: release/${{ steps.extract_version.outputs.version }}/*.dmg

      - name: Upload Snap
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-linux-snap
          path: release/${{ steps.extract_version.outputs.version }}/*.snap
      - name: Upload AppImage
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-linux-appimage
          path: release/${{ steps.extract_version.outputs.version }}/*.AppImage
      - name: Upload deb
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-linux-deb
          path: release/${{ steps.extract_version.outputs.version }}/*.deb
      - name: Upload rpm
        if: matrix.os == 'ubuntu-20.04'
        uses: actions/upload-artifact@v3
        with:
          name: reamix-dev-${{ steps.vars.outputs.sha_short }}-linux-rpm
          path: release/${{ steps.extract_version.outputs.version }}/*.rpm